#!/bin/bash
#
# Purpose:  Use scp to get analysis data and plots from the server to the local
#           machine, and untar an archive containing the plots (generated by
#           make_forward_traj_plots_onetar.sh).
# Note:     This script assumes that ~/.ssh/config and ssh keys have been set
#           up for the server.
#
# Syntax: ./scp_untar_forward_traj_plots_onetar.sh model_version_number parcel_label
#
# Example: ./scp_untar_forward_traj_plots.sh v5 1000parcel_tornadogenesis
#
# Modification History:
#   2022/06/07 - Lance Wilson:  Created.
#

if [ -z $2 ]
then
    echo "Syntax: $0 model_version_number parcel_label"
    echo "Example: $0 v5 1000parcel_tornadogenesis"
else
    version_number=$1
    parcel_label=$2

    file_label="$version_number"_"$parcel_label"

    model_fields=(dbz thpert)
    #model_fields=(dbz thpert xvort zvort u v w)

    #parcel_categories=(forward_flank up_over wraparound)
    #parcel_categories=(environment)
    parcel_categories=(forward_flank up_over wraparound environment)

    # Base directories
    #^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    server_base="~/75m_100p_$version_number/forward_traj_analysis"
    local_base="~/75m Grid Version ${version_number: -1} Parcel Images/"

    # Source Folders
    #^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    interp_dir="$server_base"/parcel_interpolation
    cat_dir="$server_base"/categorized_trajectories
    #image_dir="$server_base"/ForwardTrajectoryImages
    image_dir="$server_base"/full_output/

    output_dir=.

    # Destination Folders
    #^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    mkdir -p "$local_base"/ForwardTrajectoryNCFiles
    mkdir -p "$local_base"/CategorizedTrajectories/InitialPositions
    mkdir -p "$local_base"/CategorizedTrajectories/MeanIndices
    mkdir -p "$local_base"/CategorizedTrajectories/VortSourcePercent
    mkdir -p "$local_base"/FullImageSets/

    #^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    # Back up interpolated forward trajectory dataset.
    scp server:"$interp_dir"/cm1out_pdata_vort_interp_"$file_label".nc "$local_base"/ForwardTrajectoryNCFiles

    for parcel_category in "${parcel_categories[@]}"
    do
        #^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        # Back up initial positions of categorized trajectories.
        scp server:"$cat_dir"/"$file_label"_"$parcel_category".nc "$local_base"/CategorizedTrajectories/InitialPositions

        #^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        # Back up set of trajectories ordered by distance from a mean
        #   prognostic trajectory. 
        scp server:"$cat_dir"/index_order_from_mean/indices_from_mean_"$file_label"_"$parcel_category".npz "$local_base"/CategorizedTrajectories/MeanIndices

        #^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        # Back up text file with data about the percentage of vorticity and
        #    helicity from a category of trajectories.
        scp server:"$cat_dir"/vorticity_source_percent/"$file_label"_"$parcel_category"_vort_source.txt "$local_base"/CategorizedTrajectories/VortSourcePercent
    done

    #^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    # Back up all forward trajectory dataset images.
    cd "$local_base"/FullImageSets/

    # Get file name of most recently generated tar file.
    tar_file_name=$(ssh server 'for last_file_name in '$image_dir'/'$file_label'_*.tar; do : ; done; echo $last_file_name')

    scp server:"$tar_file_name" $output_dir

    # Untar the most recent tar file in this directory.
    for last_file_name in "$file_label"_*.tar; do : ; done; tar -xf $last_file_name

fi
